### ISSUE TITLE
TIL should support custom sources and targets

### ISSUE THREAD

**Issue by mattray** [triggermesh/til#170] opened 2021-09-07 07:38 UTC
Specifically when building new sources and targets with Koby, there should be a way to onboard new sources as a "Custom" type.

**Comment by antoineco** [comment] 2021-09-07 08:01
@mattray could that be a duplicate of #3?

**Comment by mattray** [comment] 2021-09-07 10:44
Yes, it wasn't very explicit in that issue. But as long as this is covered you can close the issue.

**Closed** 2021-09-07 10:44 UTC

**Comment by antoineco** [comment] 2021-09-07 10:56
To clarify, there will never be a generic `source custom "foo"` or `target custom "foo"` because HCL needs to know about the schema of the configuration ahead of time, and this schema is a black box when using Koby because users could declare anything. Same reason why Terraform doesn't have a generic provider for Kubernetes and only supports its base building blocks.

However, we do want to allow people to write their own translators so that TIL can support `source my_custom_source "foo"`  or `target my_custom_source "foo"` (not limited to sources/targets but using these for the example).

Internally, a simple translator looks [like this](https://github.com/triggermesh/til/blob/main/internal/components/sources/aws_codecommit.go). We want to define the helpers and interfaces so that people can write their own.
